#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1584561638                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Say hello to mello. Sleep sounds to soothe your soul.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Christopher Morales                               
your_link                                 : https://emilbaehr.com                     
your_city                                 : Florida                                
email_address                             : themelloapp@gmail.com
facebook_username                         :                                           
instagram_username                        : mellosleepsounds
twitter_username                          : mellosounds
github_username                           : themelloapp
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Beautiful UI
    description                           : From the minds behind the Backdrops app comes a gorgeous, simple user interface with calming colors that you're going to love.
    fontawesome_icon_name                 : magic
    
  - title                                 : Over 130+ Sounds & Growing
    description                           : Featuring a variety of soothing sounds such as water, nature, birds, fireplace, animals, melodies, lullabies, white noise and more.
    fontawesome_icon_name                 : music

  - title                                 : Keeping You Calm
    description                           : Mello helps with falling asleep quicker, relieving insomnia, meditation, improving your mood, relaxing, focusing and relieving anxiety and stress.
    fontawesome_icon_name                 : brain

  - title                                 : Curated Mixes
    description                           : Enjoy a varied selection of relaxing soundscapes created in-house for you to dive in and escape the world.
    fontawesome_icon_name                 : list-alt

  - title                                 : Custom Mixes
    description                           : Create and save your very own soundscapes by easily mixing sounds and volumes until you find that perfect melodic match.
    fontawesome_icon_name                 : list-ul
  
  - title                                 : Match Your Mood
    description                           : Select from a clean palette of mellow accent colors to theme the app to your very own liking.
    fontawesome_icon_name                 : palette

  - title                                 : No Ads
    description                           : Not a single ad appears within Mello. We're trying to reduce stress, not add to it. We love it too.
    fontawesome_icon_name                 : ban

  - title                                 : Bedtime Reminder
    description                           : A healthy sleep schedule makes for a healthy lifestyle. Easily set your perfect time to begin to unwind.
    fontawesome_icon_name                 : bed

  - title                                 : Mello+
    description                           : Unlock the full experience with Mello+, our affordable subscription which unlocks all sounds, mixes and features to enjoy.
    fontawesome_icon_name                 : star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#cfd2d7"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.0

device_color                              : white                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#0e1c31"

link_color                                : "#6183b6"

app_title_color                           : "#cfd2d7"
app_price_color                           : "#cfd2d7"
app_description_color                     : "#cfd2d7"

feature_title_color                       : "#cfd2d7"
feature_text_color                        : "#3b4e66"

feature_icons_foreground_color            : "#0e1c31"
feature_icons_background_color            : "#5785bb"

social_icons_foreground_color             : "#5785bb"
social_icons_background_color             : "#0e1c31"

footer_text_color                         : "#6183b6"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
